language: node_js
node_js:
- '0.10'
notifications:
  email:
  - sascha.feldmann@gmx.de
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js && rm -rf ./coverage
deploy:
  provider: heroku
  api_key:
    secure: Sun8AZKcwf4OqZfZpu9yR3VvHzdhvObOnACbS0h9tCmdGvV4cDJbC0DpnGf8hVcGva3+3UwBbxqMNpsZu9pNIBt9lKGKHFlt1/4BV3EKV3y6ljfDLWqpZCv4bxwebVGX6MV0aXtuqSodeNVJqGu8cq0oUctcpsmkiwJK0BgxTok=
  app: neeedo-webapp
  on:
    repo: neeedo/neeedo-sails
